name: Master UI/Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Build and Test
    runs-on: macOS-latest
    strategy:
        matrix:
            destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 8', 'platform=iOS Simulator,OS=13.3,name=iPhone 8 Plus', 'platform=iOS Simulator,OS=13.3,name=iPhone 11', 'platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro', 'platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro Max']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build Project
        run: xcodebuild clean build-for-testing -scheme TicTacToe -destination "${{matrix.destination}}"
      - name: Run Unit Tests
        run: xcodebuild test-without-building -scheme TicTacToe -destination "${{matrix.destination}}" -only-testing TicTacToeTests
      - name: Run UI Tests
        run: xcodebuild test-without-building -scheme TicTacToe -destination "${{matrix.destination}}" -only-testing TicTacToeUITests
