name: Master UI/Unit Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Build and Test
    runs-on: macOS-latest
    strategy:
        matrix:
            destination: ['platform=iOS Simulator,name=iPad (8th generation)', 'platform=iOS Simulator,name=iPad Air (4th generation)', 'platform=iOS Simulator,name=iPad Pro (9.7-inch)', 'platform=iOS Simulator,name=iPad Pro (11-inch) (2nd generation)', 'platform=iOS Simulator,name=iPad Pro (11-inch) (3rd generation)', 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (4th generation)', 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (5th generation)', 'platform=iOS Simulator,name=iPhone 8', 'platform=iOS Simulator,name=iPhone 8 Plus', 'platform=iOS Simulator,name=iPhone 11', 'platform=iOS Simulator,name=iPhone 11 Pro', 'platform=iOS Simulator,name=iPhone 11 Pro Max', 'platform=iOS Simulator,name=iPhone 12', 'platform=iOS Simulator,name=iPhone 12 Pro', 'platform=iOS Simulator,name=iPhone 12 Pro Max', 'platform=iOS Simulator,name=iPhone 12 mini', 'platform=iOS Simulator,name=iPhone SE (2nd generation)']
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build Project
      run: xcodebuild clean build-for-testing -scheme "EZ Tic Tac Toe" -destination "${{matrix.destination}}"
    - name: Run Unit Tests
      run: xcodebuild test-without-building -scheme "EZ Tic Tac Toe" -destination "${{matrix.destination}}" -only-testing "EZ Tic Tac ToeTests"
    - name: Run UI Tests
      run: xcodebuild test-without-building -scheme "EZ Tic Tac Toe" -destination "${{matrix.destination}}" -only-testing "EZ Tic Tac ToeUITests"
